### ISSUE TITLE
Build for freebsd 13.1 fail.

### ISSUE THREAD

**Issue by aleksander-haugas** [scala-network/Scala#16]
hi following the building manual for freebsd, on freebsd 13.1 i get this errors. in another version of freebsd works well need to touch little bit with fpic... and shared libraries but works.
thx. im building with gmake.

3 warnings generated.
[ 94%] Linking CXX executable ../../bin/scala-wallet-rpc
ld: error: /usr/local/lib/libpgm.so: undefined reference to sched_getaffinity@FBSD_1.7 [--no-allow-shlib-undefined]
c++: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[3]: *** [src/wallet/CMakeFiles/wallet_rpc_server.dir/build.make:147: bin/scala-wallet-rpc] Error 1
gmake[3]: Leaving directory '/usr/home/xlawallet/scala/build/FreeBSD/master/release'
gmake[2]: *** [CMakeFiles/Makefile2:2845: src/wallet/CMakeFiles/wallet_rpc_server.dir/all] Error 2
gmake[2]: Leaving directory '/usr/home/xlawallet/scala/build/FreeBSD/master/release'
gmake[1]: *** [Makefile:146: all] Error 2
gmake[1]: Leaving directory '/usr/home/xlawallet/scala/build/FreeBSD/master/release'
gmake: *** [Makefile:104: release-all] Error 2

**Comment by aleksander-haugas** [comment]
this is neccesary in freebsd 
`git submodule sync && git submodule update`

use /bin/sh instead of tsch

Disable crash logs
export CXXFLAGS="${CXXFLAGS} -DELPP_FEATURE_CRASH_LOG"

gmake -j2 cxxflags=-fPIC cflags=-fPIC

[ 99%] Linking CXX executable ../../bin/scalad
ld: error: can't create dynamic relocation R_X86_64_32 against local symbol in readonly segment; recompile object files with -fPIC or pass '-Wl,-z,notext' to allow text relocations in the output
>>> defined in ../../external/miniupnp/miniupnpc/libminiupnpc.a(miniupnpc.c.o)
>>> referenced by miniupnpc.c
>>>               miniupnpc.c.o:(simpleUPnPcommand) in archive ../../external/miniupnp/miniupnpc/libminiupnpc.a

**Comment by hayzamjs** [comment]
You need to compile object files with the fPIC flag.
