### ISSUE TITLE
Support for password authentication was removed on August 13, 2021.

### ISSUE THREAD

**Issue by keefer223** [scala-network/Scala#23]
git clone --recursive https://github.com/scala-project/scala
Cloning into 'scala'...
Username for 'https://github.com': keefer223
Password for 'https://keefer223@github.com': 
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/scala-project/scala/'

I took a major crash and lost most everything. As Such, I trying to rebuild the system from scratch. Your authentication is broke.

**Comment by hayzamjs** [comment]
It's https://github.com/scala-network/scala **NOT** scala-project/scala. Also the authentication system is not "broke", we don't maintain that, github does. If you try to clone a private repo or a non-existent one it will ask you to authenticate.

**Comment by keefer223** [comment]
thanks, I didn't catch that.. I've been Finger F/?.@ it for several hours 1 file at a time.

Just tried it again.. :) Thanks

**Comment by keefer223** [comment]
I didn't catch the error "git clone --recursive https://github.com/scala-project/scala"  

your directions in the websites readme file has the error, that's why I didn't catch the typo, 

used git clone --recursive https://github.com/scala-network/scala  working like a champ  thanks
