### ISSUE TITLE
Unable to open wallet 

### ISSUE THREAD

**Issue by ahmyi** [scala-network/Scala#5]
```
Error: failed to load wallet: basic_string::_M_replace_aux
Error: You may want to remove the file "wallet" and try again
```
If we are using wallets from latest daemon v7.5.1 the wallet file throws an error. Solution is to restore back by seed. Are we going to implement as v7.5's open wallet?

**Comment by hayzamjs** [comment]
I think we should just force users to restore from seed it might be the simplest solution
